name: Autoware Auto build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@0.0.18
      with:
        required-ros-distributions: dashing melodic

    - run: pwd && mkdir test && cd test
    - run: git clone https://github.com/rigtorp/udpreplay.git && ls && \
        cd udpreplay && \
        mkdir build && cd build && \
        cmake .. && \
        make install && \
        cd ../.. && rm -r udpreplay

      #"source /opt/ros/dashing/setup.bash && ros2 run --help"

    #- name: Upload Logs
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: colcon-logs
    #    path: ros_ws/log
    #  if: always()
