name: Autoware Auto build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
    - name: Setup ROS
      uses: ros-tooling/setup-ros@0.0.18
      with:
        required-ros-distributions: melodic

    - name: Build AutowareAuto
      run: |
        source /opt/ros/melodic/setup.bash
        mkdir -p autoware.ai/src
        cd autoware.ai
        wget -O autoware.ai.repos "https://gitlab.com/autowarefoundation/autoware.ai/autoware/raw/master/autoware.ai.repos?inline=false"
        vcs import src < autoware.ai.repos
        rosdep update
        rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release

    #- name: Upload Logs
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: colcon-logs
    #    path: ros_ws/log
    #  if: always()
