name: ROS2 test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@0.0.18
      with:
        required-ros-distributions: dashing eloquent

    - name: Remove demo packages
      run: apt-get autoremove ros-$ROS_DISTRO-demo-nodes-cpp

    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.0.16
      with:
        package-name: demo_nodes_cpp demo_nodes_cpp_native demo_nodes_py

    - name: Upload Logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()
